# Change these first
owner: Wronnay # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Server
    url: http://s3.wronnay.net
  - name: Blog
    url: https://blog.wronnay.net
  - name: Kanboard
    url: https://kb.wronnay.net
  - name: Gitea
    url: https://git.kernel.fun/
  - name: WebPage4.Me
    url: https://webpage4.me

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.wronnay.net
  # baseUrl: /your-repo-name
  logoUrl: https://blog.wronnay.net/wronnay_logo.png
  name: Wronnay Status
  introTitle: "Current Status of the Systems"
  introMessage: See if something is affected.
  navbar:
    - title: Status
      href: /
    - title: Twitter
      href: https://twitter.com/Wronnay
    - title: Privacy Policy
      href: https://blog.wronnay.net/datenschutzerklaerung/
    - title: Imprint
      href: https://blog.wronnay.net/impressum/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
